### ISSUE TITLE
Crash on FreeBSD/arm during service (re)start

### ISSUE THREAD

**Issue by samm-git** [bsdtrhodes/freebsd-fscd#7]
fscd crashing on restart attempt, tracedump is attached:

```
(gdb) run -c /usr/local/etc/fscd.conf -f -vvvv
Starting program: /usr/ports/sysutils/fsc/work/freebsd-fscd-ac80298/fscd/fscd -c /usr/local/etc/fscd.conf -f -vvvv
domoticz is running as pid 56228.
ebusd is running as pid 56372.

Program received signal SIGSEGV, Segmentation fault.
0x0000b72c in wait_restart (var=0x20611020) at fscd.c:433
433					SLIST_REMOVE(&svs->svpids, svpid, spid, next);
Current language:  auto; currently minimal
(gdb) bt full
#0  0x0000b72c in wait_restart (var=0x20611020) at fscd.c:433
	curelm = (struct spid *) 0x0
	inputv = (struct restart_params *) 0x20611020
	svs = (struct service *) 0x2063f010
	svpid = (struct spid *) 0x3e8
	retries = 6
#1  0x20079710 in thread_start (curthread=0x20612600) at /usr/src/lib/libthr/thread/thr_create.c:290
	set = <value optimized out>
#2  0x20079188 in _pthread_create (thread=Error accessing memory address 0xbf2fd010: Bad address.
) at /usr/src/lib/libthr/thread/thr_create.c:186
	ret = 0
	cpusetsize = Error accessing memory address 0xbf2fd008: Bad address.
(gdb)
```

I am running fscd and killing one of the servies (ebusd). At this point fscd crashing. 

Some of the gdb data:

```
(gdb) print *svs
$2 = {svname = 0x20616180 "ebusd", svpids = {slh_first = 0x0}, next = {sle_next = 0x2063f000}}
(gdb) print *svpid
Error accessing memory address 0x3e8: Bad address.
(gdb)
```

**Comment by bsdtrhodes** [comment]
Change merged, sorry it was late but thanks for the help!
